site_name: Optimus API
nav:
   - "Home": index.md
   - "Obtain a License": ObtainLicense.md
   - "License Verification": LicenseVerification.md
   - "List Available Benchmarks": ListAvailableBenchmarks.md
   - "Download Benchmark Content": DownloadBenchmarkContent.md
   - "List Available CIS-CAT Versions": ListAvailableVersions.md
   - "Download CIS-CAT Full": DownloadCIS-CATFull.md
   - "Download CIS-CAT Lite": DownloadCIS-CATLite.md

   - "Change Log": Change Log.md
theme:
  name: readthedocs